#:schema node_modules/wrangler/config-schema.json

name = "go-wolfyta-dev"
main = "src/index.ts"
compatibility_date = "2024-10-22"
compatibility_flags = ["nodejs_compat"]

[observability]
enabled = true

[[unsafe.bindings]]
name = "RATE_LIMITER"
type = "ratelimit"
namespace_id = "576"
simple = { limit = 5, period = 60 }
